# Gosec security scanner configuration
# https://github.com/securecodewarrior/gosec

# Global settings
global:
  # Include test files in scan
  tests: true
  # Include vendor directory
  vendor: false
  # Exclude generated files
  exclude-generated: true

# Rule settings
rules:
  # Disable specific rules that are not applicable
  G101: # Look for hard coded passwords
    severity: high
    confidence: high
  G102: # Bind to all interfaces
    severity: medium
    confidence: medium
  G103: # Audit the use of unsafe block
    severity: high
    confidence: high
  G104: # Audit errors not checked
    severity: medium
    confidence: medium
  G106: # Audit the use of ssh.InsecureIgnoreHostKey
    severity: high
    confidence: high
  G107: # Url provided to HTTP request as taint input
    severity: medium
    confidence: medium
  G108: # Profiling endpoint is automatically exposed
    severity: medium
    confidence: medium
  G109: # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
    severity: medium
    confidence: medium
  G110: # Potential DoS vulnerability via decompression bomb
    severity: high
    confidence: medium
  G201: # SQL query construction using format string
    severity: high
    confidence: high
  G202: # SQL query construction using string concatenation
    severity: high
    confidence: high
  G203: # Use of unescaped data in HTML templates
    severity: high
    confidence: high
  G204: # Audit use of command execution
    severity: high
    confidence: high
  G301: # Poor file permissions used when creating a directory
    severity: medium
    confidence: medium
  G302: # Poor file permissions used with chmod
    severity: medium
    confidence: medium
  G303: # Creating tempfile using a predictable path
    severity: medium
    confidence: medium
  G304: # File path provided as taint input
    severity: high
    confidence: high
  G305: # File traversal when extracting zip archive
    severity: high
    confidence: high
  G306: # Poor file permissions used when writing to a file
    severity: medium
    confidence: medium
  G307: # Poor error handling with defer
    severity: medium
    confidence: medium
  G401: # Detect the usage of DES, RC4, MD5 or SHA1
    severity: high
    confidence: high
  G402: # Look for bad TLS connection settings
    severity: high
    confidence: high
  G403: # Ensure minimum RSA key length of 2048 bits
    severity: high
    confidence: high
  G404: # Insecure random number source (rand)
    severity: high
    confidence: high
  G501: # Import blocklist: crypto/md5
    severity: high
    confidence: high
  G502: # Import blocklist: crypto/des
    severity: high
    confidence: high
  G503: # Import blocklist: crypto/rc4
    severity: high
    confidence: high
  G504: # Import blocklist: net/http/cgi
    severity: medium
    confidence: medium
  G505: # Import blocklist: crypto/sha1
    severity: high
    confidence: high
  G601: # Implicit memory aliasing in for loop
    severity: medium
    confidence: medium

# Exclude patterns
exclude:
  # Exclude test files from certain rules
  - "**/*_test.go"
  # Exclude vendor directory
  - "vendor/**"
  # Exclude generated files
  - "**/*.pb.go"
  - "**/*.gen.go"

# Include patterns
include:
  - "**/*.go"

# Output format
format: json
output: gosec-report.json

# Severity threshold
severity: medium
confidence: medium
