name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["molmedoz"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command 'gopher ...'
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system?
      placeholder: e.g., Ubuntu 22.04, macOS 13.0, Windows 11
    validations:
      required: true

  - type: input
    id: gopher-version
    attributes:
      label: Gopher Version
      description: What version of Gopher are you using?
      placeholder: e.g., v0.1.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: e.g., go1.21.0
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Command Output
      description: Include the full output of the command that failed
      placeholder: Paste the command output here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Include your Gopher configuration (if relevant)
      placeholder: |
        ```json
        {
          "install_dir": "...",
          "download_dir": "...",
          ...
        }
        ```
      render: json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...
