name: Docker

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

# Cancel previous runs if new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.base
          push: false
          tags: |
            gopher:latest
            gopher:${{ github.sha }}
            ${{ steps.version.outputs.version && format('gopher:v{0}', steps.version.outputs.version) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Test Docker image
        run: |
          echo "Testing Docker image functionality..."
          docker run --rm gopher:latest gopher version
          docker run --rm gopher:latest gopher help
          docker run --rm gopher:latest gopher list --no-interactive
          docker run --rm gopher:latest gopher list-remote --no-interactive --page-size 5
          echo "✅ Docker image tests passed!"